version: "3.9"
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:hdgxtmkjtx39@db:5432/jobtracker
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hdgxtmkjtx39
      POSTGRES_DB: job-tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
